AWSConfigurationTemplateVersion: 1.1.0.0
EnvironmentConfigurationMetadata:
  DateCreated: '1496079463000'
  DateModified: '1496079609235'
  Description: Configuration created from the EB CLI using "eb config save".
EnvironmentTier:
  Name: WebServer
  Type: Standard
OptionSettings:
  aws:autoscaling:asg:
    Custom Availability Zones: us-west-2a
  aws:autoscaling:launchconfiguration:
    EC2KeyName: MyFirstInstance
    IamInstanceProfile: aws-elasticbeanstalk-ec2-role
    InstanceType: t2.micro
  aws:autoscaling:updatepolicy:rollingupdate:
    RollingUpdateEnabled: true
    RollingUpdateType: Health
  aws:elasticbeanstalk:command:
    BatchSize: '30'
    BatchSizeType: Percentage
  aws:elasticbeanstalk:container:php:phpini:
    composer_options: --no-dev
    document_root: /public
  aws:elasticbeanstalk:environment:
    EnvironmentType: SingleInstance
    ServiceRole: aws-elasticbeanstalk-service-role
  aws:elasticbeanstalk:healthreporting:system:
    SystemType: enhanced
Platform:
  PlatformArn: arn:aws:elasticbeanstalk:us-west-2::platform/PHP 7.0 running on 64bit
    Amazon Linux/2.4.0
